xcopy ..\NFTCalvi\src\app\authent\*.* src\app\authent\
xcopy ..\NFTCalvi\src\app\network.service.ts src\app\
xcopy ..\NFTCalvi\src\app\user.service.ts src\app\
xcopy ..\NFTCalvi\src\app\operation.service.ts src\app\
xcopy ..\NFTCalvi\src\app\hourglass\*.*  src\app\hourglass\
xcopy ..\NFTCalvi\src\app\scanner\*.*  src\app\scanner\
xcopy ..\NFTCalvi\src\operation.ts src\
xcopy ..\NFTCalvi\src\create.ts src\
xcopy ..\NFTCalvi\src\tools.ts src\
xcopy ..\NFTCalvi\src\nft.ts src\
