xcopy /f /y ..\NFTCalvi\src\app\authent\*.* src\app\authent\
xcopy /f /y ..\NFTCalvi\src\app\payment\*.* src\app\payment\
xcopy /f /y ..\NFTCalvi\src\app\splash\*.* src\app\splash\
xcopy /f /y ..\NFTCalvi\src\app\jauge\*.* src\app\jauge\
xcopy /f /y ..\NFTCalvi\src\app\autovalidator\*.* src\app\autovalidator\
xcopy /f /y ..\NFTCalvi\src\app\ask-for-payment\*.* src\app\ask-for-payment\
xcopy /f /y ..\NFTCalvi\src\app\input\*.* src\app\input\
xcopy /f /y ..\NFTCalvi\src\app\tuto\*.* src\app\tuto\
xcopy /f /y ..\NFTCalvi\src\app\prompt\*.* src\app\prompt\
xcopy /f /y ..\NFTCalvi\src\app\collection-selector\*.* src\app\collection-selector\
xcopy /f /y ..\NFTCalvi\src\app\showroom\*.* src\app\showroom\
xcopy /f /y ..\NFTCalvi\src\app\faqs\*.* src\app\faqs\
xcopy /f /y ..\NFTCalvi\src\app\upload-file\*.* src\app\upload-file\
xcopy /f /y ..\NFTCalvi\src\app\network.service.ts src\app\
xcopy /f /y ..\NFTCalvi\src\app\evm-wallet-service.service.ts src\app\
xcopy /f /y ..\NFTCalvi\src\app\reversebloc\*.* src\app\reversebloc\
xcopy /f /y ..\NFTCalvi\src\app\user.service.ts src\app\

xcopy /f /y ..\NFTCalvi\src\app\filter.pipe.ts src\app\
xcopy /f /y ..\NFTCalvi\src\app\operation.service.ts src\app\
xcopy /f /y ..\NFTCalvi\src\app\style-manager.service.ts src\app\
xcopy /f /y ..\NFTCalvi\src\app\device.service.ts src\app\
xcopy /f /y ..\NFTCalvi\src\app\hourglass\*.*  src\app\hourglass\
xcopy /f /y ..\NFTCalvi\src\app\scanner\*.*  src\app\scanner\
xcopy /f /y ..\NFTCalvi\src\definitions.ts src\
xcopy /f /y ..\NFTCalvi\src\operation.ts src\
xcopy /f /y ..\NFTCalvi\src\create.ts src\
xcopy /f /y ..\NFTCalvi\src\tools.ts src\
xcopy /f /y ..\NFTCalvi\src\nfluent.ts src\
xcopy /f /y ..\NFTCalvi\src\nft.ts src\
xcopy /f /y ..\NFTCalvi\src\nfluent.scss src\
xcopy /f /y ..\NFTCalvi\src\nfluent-dark.scss src\
xcopy /f /y ..\NFTCalvi\src\styles.scss src\
