quality: 98
version: 1
message: ""
id: 186ef1382f6
height: 800
width: 800
data:
  description: ""
  files: ""
  operation: ""
  properties: ""
  symbol: token__idx__
  title: MonNFT
  tags: ""
  sequence:
    - Texte ici
  creators: ""
attributes: {}
layers:
  - params: {}
    name: fond
    elements:
      - image: https://images.unsplash.com/photo-1586074299757-dc655f18518c?ixid=Mnw5OTUyN3wwfDF8c2VhcmNofDl8fHBhcGVyfGVufDB8fHx8MTY3OTA0ODczMA&ixlib=rb-4.0.3
        name: image1
      - image: https://images.unsplash.com/photo-1615800098799-0ccb261b1f92?ixid=Mnw5OTUyN3wwfDF8c2VhcmNofDJ8fHBhcGVyfGVufDB8fHx8MTY3OTA0ODczMA&ixlib=rb-4.0.3
        name: image2
      - image: https://images.unsplash.com/photo-1586075010923-2dd4570fb338?ixid=Mnw5OTUyN3wwfDF8c2VhcmNofDR8fHBhcGVyfGVufDB8fHx8MTY3OTA0ODczMA&ixlib=rb-4.0.3
        name: image3
      - image: https://images.unsplash.com/photo-1603484477859-abe6a73f9366?ixid=Mnw5OTUyN3wwfDF8c2VhcmNofDV8fHBhcGVyfGVufDB8fHx8MTY3OTA0ODczMA&ixlib=rb-4.0.3
        name: image4
      - image: https://images.unsplash.com/photo-1528458965990-428de4b1cb0d?ixid=Mnw5OTUyN3wwfDF8c2VhcmNofDEwfHxwYXBlcnxlbnwwfHx8fDE2NzkwNDg3MzA&ixlib=rb-4.0.3
        name: image5
      - image: https://images.unsplash.com/photo-1616410731303-6affae095a0a?ixid=Mnw5OTUyN3wwfDF8c2VhcmNofDh8fHBhcGVyfGVufDB8fHx8MTY3OTA0ODczMA&ixlib=rb-4.0.3
        name: image6
    text: ""
    unique: false
    width: 800
    height: 800
    indexed: true
    position: 0
    translation: 0,0
    scale: 1,1
    margin: 0,0
  - params: {}
    name: text_logo
    elements:
      - image: "https://nfluent.io/assets/certificat_authenticite_black.svg"
        type: image/svg
      - image: "https://nfluent.io/assets/certificat_authenticite_white.svg"
        type: image/svg
    text: ""
    unique: false
    width: 800
    height: 800
    indexed: true
    position: 1
    translation: 0,0
    scale: 1,1
    margin: 0,0
limit: 5
help: ""
max_items: 11
label: localConfig
platform:
  label: ""
  value: ""
seed: 0
text:
  color: "#FFFFFF"
  fontsize: 12
  position_text:
    x: 10
    y: 10
  text_to_add: Texte ici
  font:
    name: Corbel
    file: corbel.ttf
location: localConfig.yaml
